In [1]:
import os

In [2]:
import numpy as np

In [3]:
import matplotlib.pylab as plt

In [4]:
from PIL import Image

In [5]:
rootDir = "photos"

In [6]:
array = np.zeros([20, 200, 200, 3])

In [7]:
re_img = []

In [8]:
for dirName, subdirList, fileList in os.walk(rootDir):
    print('Found directory: %s' % dirName)   
    for fname in fileList:
        print('file name: \t%s' % fname)
        print('Found directory: %s' % dirName)
        #i = plt.imread(fname)
        i = Image.open(dirName+"/"+fname)
        resize = i.resize((200,200))
        np_re_img = np.array(resize)
        re_img.append(np_re_img)

Found directory: photos
file name: 	1.jpg
Found directory: photos
file name: 	10.jpg
Found directory: photos
file name: 	11.jpg
Found directory: photos
file name: 	12.jpg
Found directory: photos
file name: 	13.jpg
Found directory: photos
file name: 	14.jpg
Found directory: photos
file name: 	15.jpg
Found directory: photos
file name: 	16.jpg
Found directory: photos
file name: 	17.jpg
Found directory: photos
file name: 	18.jpg
Found directory: photos
file name: 	19.jpg
Found directory: photos
file name: 	2.jpg
Found directory: photos
file name: 	20.jpg
Found directory: photos
file name: 	3.jpg
Found directory: photos
file name: 	4.jpg
Found directory: photos
file name: 	5.jpg
Found directory: photos
file name: 	6.jpg
Found directory: photos
file name: 	7.jpg
Found directory: photos
file name: 	8.jpg
Found directory: photos
file name: 	9.jpg
Found directory: photos


In [9]:
array = np.array(re_img)

In [10]:
print (array)
print (f"Array shape: {array.shape}")

[[[[ 21  49  88]
   [ 21  49  88]
   [ 22  50  89]
   ...
   [ 68  96 135]
   [ 67  95 134]
   [ 67  95 134]]

  [[ 21  49  88]
   [ 21  49  88]
   [ 22  50  89]
   ...
   [ 68  96 135]
   [ 68  96 135]
   [ 67  95 134]]

  [[ 21  49  88]
   [ 22  50  89]
   [ 22  50  89]
   ...
   [ 69  97 136]
   [ 69  97 136]
   [ 68  96 135]]

  ...

  [[200 209 214]
   [190 200 209]
   [179 189 199]
   ...
   [135 145 157]
   [150 162 174]
   [138 150 162]]

  [[191 200 205]
   [191 200 207]
   [185 193 204]
   ...
   [173 183 195]
   [196 208 220]
   [167 181 194]]

  [[208 204 203]
   [202 201 199]
   [211 211 209]
   ...
   [176 181 187]
   [199 204 208]
   [183 187 190]]]


 [[[ 70 102 143]
   [ 46  79 120]
   [ 47  80 121]
   ...
   [ 45  80 120]
   [ 45  80 120]
   [ 45  80 120]]

  [[ 69  98 138]
   [ 59  91 130]
   [ 57  89 128]
   ...
   [ 45  80 120]
   [ 45  80 120]
   [ 45  80 120]]

  [[ 98 124 159]
   [ 68  94 129]
   [ 61  90 124]
   ...
   [ 45  80 120]
   [ 45  80 120]
   [ 45  80