In [19]:
import os, os.path

In [20]:
import numpy as np

In [21]:
import matplotlib.pylab as plt

In [22]:
from PIL import Image

In [44]:
def initialize_folder():
    global rootDir
    global onlyfiles
    global file_length
    rootDir = "photos"
    onlyfiles = next(os.walk(rootDir))[2]#third element of file array
    file_length = len(onlyfiles)
    print (f"files in the folder: {file_length}")

In [45]:
def arrays():
    global array
    global re_img
    array = np.zeros([file_length, 200, 200, 3])
    re_img = []

In [46]:
def resizing():
    global re_img
    for dirName, subdirList, fileList in os.walk(rootDir):
        print('Found directory: %s' % dirName)   
        for fname in fileList:
            i = Image.open(dirName+"/"+fname)
            resize = i.resize((200,200))
            np_re_img = np.array(resize)
            re_img.append(np_re_img)
        

In [47]:
def appending_in_main_array():
    array = np.array(re_img)
    print (f"Resized array: \n{array}")
    print (f"Array shape: {array.shape}")

In [48]:
def main():
    initialize_folder()
    arrays()
    resizing()
    appending_in_main_array()

In [49]:
main()

files in the folder: 20
Found directory: photos
Resized array: 
[[[[ 21  49  88]
   [ 21  49  88]
   [ 22  50  89]
   ...
   [ 68  96 135]
   [ 67  95 134]
   [ 67  95 134]]

  [[ 21  49  88]
   [ 21  49  88]
   [ 22  50  89]
   ...
   [ 68  96 135]
   [ 68  96 135]
   [ 67  95 134]]

  [[ 21  49  88]
   [ 22  50  89]
   [ 22  50  89]
   ...
   [ 69  97 136]
   [ 69  97 136]
   [ 68  96 135]]

  ...

  [[200 209 214]
   [190 200 209]
   [179 189 199]
   ...
   [135 145 157]
   [150 162 174]
   [138 150 162]]

  [[191 200 205]
   [191 200 207]
   [185 193 204]
   ...
   [173 183 195]
   [196 208 220]
   [167 181 194]]

  [[208 204 203]
   [202 201 199]
   [211 211 209]
   ...
   [176 181 187]
   [199 204 208]
   [183 187 190]]]


 [[[ 70 102 143]
   [ 46  79 120]
   [ 47  80 121]
   ...
   [ 45  80 120]
   [ 45  80 120]
   [ 45  80 120]]

  [[ 69  98 138]
   [ 59  91 130]
   [ 57  89 128]
   ...
   [ 45  80 120]
   [ 45  80 120]
   [ 45  80 120]]

  [[ 98 124 159]
   [ 68  94 129]
   [ 