In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3, 4]
type(my_list)

list

In [3]:
my_array = np.array(my_list)
print (my_array)
type (my_array)

[1 2 3 4]


numpy.ndarray

In [4]:
my_zero = np.zeros(my_list) #each element multiplied
print(my_zero)
type(my_zero)

[[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]]


numpy.ndarray

In [5]:
my_one = np.ones(10)
print(my_one)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
empty = np.empty(4)
print(empty)

[1.27734658e-152 7.20191309e+159 2.43812981e-152 1.24033557e+224]


In [7]:
arange = np.arange(5)

In [8]:
print (arange)

[0 1 2 3 4]
