In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])

In [3]:
type(x)

numpy.ndarray

In [4]:
x.ndim

1

In [5]:
y = np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
z = np.arange(0,15).reshape(5,3)
z

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [7]:
z.shape

(5, 3)

In [10]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])